// <auto-generated />
using System;
using EFlabDay2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFlabDay2.Migrations
{
    [DbContext(typeof(BlogContext))]
    [Migration("20230528113551_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFlabDay2.Models.News", b =>
                {
                    b.Property<int>("News_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("News_id"));

                    b.Property<DateTime>("News_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("News_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News_reff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News_title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("News_id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("EFlabDay2.Models.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<string>("User_add")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_age")
                        .HasColumnType("int");

                    b.Property<string>("User_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_password")
                        .HasColumnType("int");

                    b.Property<string>("User_photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFlabDay2.Models.category", b =>
                {
                    b.Property<int>("St_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("St_id"));

                    b.Property<string>("St_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("St_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("St_id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
