// <auto-generated />
using System;
using EFlabDay2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFlabDay2.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class ITIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFlabDay2.Models.News", b =>
                {
                    b.Property<int>("News_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("News_id"));

                    b.Property<int?>("Cat_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("News_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("News_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News_photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News_reff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_id")
                        .HasColumnType("int");

                    b.HasKey("News_id");

                    b.HasIndex("Cat_id");

                    b.HasIndex("User_id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("EFlabDay2.Models.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<string>("User_add")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_age")
                        .HasColumnType("int");

                    b.Property<string>("User_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("User_password")
                        .HasColumnType("int");

                    b.Property<string>("User_photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EFlabDay2.Models.category", b =>
                {
                    b.Property<int>("St_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("St_id"));

                    b.Property<string>("St_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("St_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("St_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EFlabDay2.Models.News", b =>
                {
                    b.HasOne("EFlabDay2.Models.category", "Category")
                        .WithMany("News")
                        .HasForeignKey("Cat_id");

                    b.HasOne("EFlabDay2.Models.User", "User")
                        .WithMany("News")
                        .HasForeignKey("User_id");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EFlabDay2.Models.User", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("EFlabDay2.Models.category", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
